let data = TIMEWISE_DATA.getMonth('2026-08');
const content = document.querySelector('#appContent');
const title = document.querySelector('#pageTitle');
const eyebrow = document.querySelector('#eyebrow');
let activeView = 'overview', teamFilter = 'all', selectedEmployee = null;
const hours = n => `${n.toLocaleString()}h`;
const initials = name => name.split(' ').map(x=>x[0]).join('').slice(0,2);
let employees, compliant, missing, totalExpected, totalBooked, totalLeave;
function setMonth(key){
  data = TIMEWISE_DATA.getMonth(key);
  employees = data.employees;
  compliant = employees.filter(e=>!e.missingHours);
  missing = employees.filter(e=>e.missingHours);
  totalExpected = employees.reduce((a,e)=>a+e.expected,0);
  totalBooked = employees.reduce((a,e)=>a+e.booked,0);
  totalLeave = employees.reduce((a,e)=>a+e.leaveHours,0);
}
setMonth('2026-08');
const pct = (a,b)=>Math.round(a/b*100);
function toast(message){ const el=document.querySelector('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2500); }
function statusPill(status){ return `<span class="status ${status==='Missing entries'?'missing':status==='Leave matched'?'leave':'complete'}"><i></i>${status}</span>`; }
function card(title, body, sub='', action=''){return `<article class="card"><div class="card-header"><div><h3>${title}</h3>${sub?`<p>${sub}</p>`:''}</div>${action}</div>${body}</article>`;}
function kpi(label,value,note,tone=''){return `<article class="kpi card"><div class="kpi-label"><span>${label}</span><span class="kpi-icon ${tone}">◌</span></div><strong>${value}</strong><p class="${tone}">${note}</p></article>`;}
function weeklyRows(){ return data.weeks.map(({id,label,shortLabel,dates})=>{const relevant=employees.flatMap(e=>e.bookings.filter(b=>b.week===id));const booked=relevant.filter(b=>b.type==='Booked').reduce((a,b)=>a+b.hours,0),leave=relevant.filter(b=>b.project==='Leave').reduce((a,b)=>a+b.hours,0),expected=employees.length*dates.length*8-leave,good=employees.filter(e=>{const x=e.bookings.filter(b=>b.week===id),l=x.filter(b=>b.project==='Leave').reduce((a,b)=>a+b.hours,0),h=x.filter(b=>b.type==='Booked').reduce((a,b)=>a+b.hours,0);return h===dates.length*8-l;}).length;return{id,label,shortLabel,dates,booked,leave,expected,good};});}
function bar(value,max,kind='blue'){return `<div class="bar"><i class="${kind}" style="width:${Math.max(4,Math.min(100,value/max*100))}%"></i></div>`;}
function overview(){const weeks=weeklyRows(); return `
  <section class="page-intro"><div><h2>Month-end timesheet health</h2><p>See who is ready to close ${data.month}, and follow up before payroll cut-off.</p></div><div class="intro-actions"><span class="month-chip">${data.month}</span><button class="primary-button" id="reviewMissing">Review missing entries <span>→</span></button></div></section>
  <section class="kpi-grid">${kpi('TEAM COMPLETION',`${pct(compliant.length,employees.length)}%`,`${compliant.length} of ${employees.length} employees are compliant`,'success')}${kpi('MISSING ENTRIES',missing.length,`${hours(missing.reduce((a,e)=>a+e.missingHours,0))} still needs to be booked`,'danger')}${kpi('BOOKED HOURS',hours(totalBooked),`${pct(totalBooked,totalExpected)}% of expected work hours`,'')}${kpi('LEAVE MATCHED',hours(totalLeave),`${employees.filter(e=>e.leaveHours).length} employees with approved leave`,'purple')}</section>
  <section class="overview-grid">
    ${card('Completion by week', `<div class="chart-header"><span>Employees with correct hours</span><span class="legend"><i></i> Complete <i class="leave-dot"></i> Leave matched</span></div><div class="weekly-chart">${weeks.map(w=>`<div class="week-row"><div><b>${w.id}</b><small>${w.shortLabel}</small></div>${bar(w.good,50,'teal')}<strong>${w.good}/50</strong></div>`).join('')}</div>`, 'Weekly time sheet completion')}
    ${card('Hours at a glance', `<div class="ring-row"><div class="ring" style="--p:${pct(totalBooked,totalExpected)}"><div><b>${pct(totalBooked,totalExpected)}%</b><small>booked</small></div></div><div class="hour-summary"><div><span>Expected work</span><b>${hours(totalExpected)}</b></div><div><span>Booked to projects</span><b>${hours(totalBooked)}</b></div><div><span>Approved leave</span><b>${hours(totalLeave)}</b></div></div></div>`, 'Leave is excluded from expected work hours')}
  </section>
  <section class="lower-grid">
    ${card('Needs manager attention', `<div class="attention-list">${missing.slice(0,5).map(e=>`<button class="attention-row employee-open" data-id="${e.id}"><span class="employee-avatar danger">${initials(e.name)}</span><span><b>${e.name}</b><small>${e.projects.join(' · ')}</small></span><strong>${hours(e.missingHours)} missing</strong><span class="chevron">›</span></button>`).join('')}</div>`, `${missing.length} employees have unfilled days`, `<button class="link-button" id="viewAllAttention">View all <span>→</span></button>`)}
    ${card('Project hours booked', `<div class="project-list">${data.projects.slice(0,5).map(p=>{const h=employees.reduce((a,e)=>a+e.bookings.filter(b=>b.project===p[1]).reduce((x,b)=>x+b.hours,0),0);return `<div><span><i></i>${p[1]}</span><b>${hours(h)}</b>${bar(h,1000,['teal','purple','orange','blue','pink'][data.projects.indexOf(p)%5])}</div>`}).join('')}</div>`, 'Top five projects by recorded effort', `<button class="link-button" data-view-target="projects">View allocation <span>→</span></button>`)}</section>`;}
function team(){ const results=teamFilter==='all'?employees:teamFilter==='missing'?missing:compliant;return `<section class="page-intro"><div><h2>Team compliance</h2><p>Review every employee’s ${data.month} bookings, leave, and outstanding time.</p></div><div class="intro-actions"><label class="search"><span>⌕</span><input id="employeeSearch" placeholder="Search employee"></label><button class="select-button">All projects ⌄</button></div></section><section class="team-summary"><span><b>${employees.length}</b> employees</span><span><i></i><b>${compliant.length}</b> complete or leave matched</span><span><i class="red-dot"></i><b>${missing.length}</b> need attention</span></section><div class="filter-tabs"><button class="filter-tab ${teamFilter==='all'?'active':''}" data-filter="all">All employees</button><button class="filter-tab ${teamFilter==='missing'?'active':''}" data-filter="missing">Needs attention <b>${missing.length}</b></button><button class="filter-tab ${teamFilter==='complete'?'active':''}" data-filter="complete">Complete <b>${compliant.length}</b></button></div>${card('Employee time sheet status', `<div class="table-scroll"><table><thead><tr><th>EMPLOYEE</th><th>ASSIGNED PROJECTS</th><th>EXPECTED</th><th>BOOKED</th><th>LEAVE</th><th>MISSING</th><th>STATUS</th><th></th></tr></thead><tbody id="teamRows">${teamRows(results)}</tbody></table></div>`, `${data.month} · ${data.dates.length} working days`)}`;}
function teamRows(list){return list.map(e=>`<tr class="${e.missingHours?'row-alert':''}"><td><button class="person employee-open" data-id="${e.id}"><span class="employee-avatar ${e.missingHours?'danger':''}">${initials(e.name)}</span><span><b>${e.name}</b><small>${e.id} · ${e.role}</small></span></button></td><td><span class="project-tags">${e.projects.map(p=>`<em>${p.replace(' ',' ')}</em>`).join('')}</span></td><td>${hours(e.expected)}</td><td><b>${hours(e.booked)}</b></td><td>${e.leaveHours?hours(e.leaveHours):'—'}</td><td class="missing-hours">${e.missingHours?hours(e.missingHours):'—'}</td><td>${statusPill(e.status)}</td><td>${e.missingHours?`<button class="mail-button send-reminder" data-name="${e.name}" title="Send reminder">✉</button>`:'<button class="more-button employee-open" data-id="'+e.id+'">›</button>'}</td></tr>`).join('');}
function projects(){return `<section class="page-intro"><div><h2>Project allocation</h2><p>Where the team’s ${data.month} effort has been booked across active initiatives.</p></div><div class="intro-actions"><span class="month-chip">${data.month}</span><button class="select-button">Export report ↓</button></div></section><section class="project-kpis">${kpi('ACTIVE PROJECTS','10','All projects have recorded time','success')}${kpi('TOTAL PROJECT HOURS',hours(totalBooked),'Across 50 team members','')}${kpi('AVG. PROJECTS / EMPLOYEE','2.0','Each employee is assigned two projects','purple')}</section>${card('Effort by project', `<div class="allocation">${data.projects.map((p,i)=>{const projectEmployees=employees.filter(e=>e.projects.includes(p[1]));const h=employees.reduce((a,e)=>a+e.bookings.filter(b=>b.project===p[1]).reduce((x,b)=>x+b.hours,0),0);return `<div class="allocation-row"><div><span class="project-swatch c${i%5}"></span><b>${p[1]}</b><small>${p[0]} · ${p[2]}</small></div><span>${projectEmployees.length} people</span><div>${bar(h,1100,['teal','purple','orange','blue','pink'][i%5])}</div><strong>${hours(h)}</strong></div>`}).join('')}</div>`, 'Booked hours exclude approved leave')}`;}
function employeeDrawer(e){const weekly=weeklyRows().map(w=>{const bookings=e.bookings.filter(b=>b.week===w.id),leave=bookings.filter(b=>b.project==='Leave').reduce((a,b)=>a+b.hours,0),booked=bookings.filter(b=>b.type==='Booked').reduce((a,b)=>a+b.hours,0),expected=w.dates.length*8-leave;return[w.id,booked,leave,expected,Math.max(0,expected-booked)];});return `<div class="drawer-backdrop" id="drawerClose"></div><aside class="drawer"><button class="drawer-close" id="drawerX">×</button><div class="drawer-person"><span class="employee-avatar ${e.missingHours?'danger':''}">${initials(e.name)}</span><div><p>${e.id}</p><h2>${e.name}</h2><span>${e.role}</span></div></div>${statusPill(e.status)}<div class="drawer-metrics"><div><small>Booked</small><b>${hours(e.booked)}</b></div><div><small>Expected</small><b>${hours(e.expected)}</b></div><div><small>Missing</small><b class="danger-text">${hours(e.missingHours)}</b></div></div><h3>Weekly summary</h3><div class="mini-table">${weekly.map(x=>`<div><b>${x[0]}</b><span>${x[1]} booked</span><span>${x[2]?x[2]+' leave':'— leave'}</span><strong class="${x[4]?'danger-text':''}">${x[4]?x[4]+' missing':'Complete'}</strong></div>`).join('')}</div><h3>Assigned projects</h3><div class="drawer-projects">${e.projects.map(p=>`<span>${p}</span>`).join('')}</div>${e.missingHours?`<button class="primary-button wide send-reminder" data-name="${e.name}">✉ Send time sheet reminder</button>`:''}</aside>`;}
function render(){
  // The employee panel is rendered outside the content region; clear a prior instance
  // before rendering to prevent stacked backdrops and inactive close buttons.
  document.querySelectorAll('.drawer, .drawer-backdrop').forEach(element=>element.remove());
  content.innerHTML=activeView==='overview'?overview():activeView==='team'?team():projects();
  const details=selectedEmployee?employees.find(e=>e.id===selectedEmployee):null;
  if(details) document.body.insertAdjacentHTML('beforeend',employeeDrawer(details));
  const config={overview:['Timesheet health','AUGUST 2026 · MONTH-END VIEW'],team:['Team compliance','AUGUST 2026 · TEAM REVIEW'],projects:['Project allocation','AUGUST 2026 · UTILIZATION']}[activeView];
  title.textContent=config[0];eyebrow.textContent=`${data.month.toUpperCase()} · ${config[1].split(' · ').at(-1)}`;document.querySelector('#monthSwitcher').value=data.key;document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===activeView));bind();
}
function bind(){document.querySelectorAll('.nav-link,[data-view-target]').forEach(x=>x.onclick=()=>{activeView=x.dataset.view||x.dataset.viewTarget;selectedEmployee=null;render();});const brand=document.querySelector('.brand');if(brand)brand.onclick=event=>{event.preventDefault();activeView='overview';teamFilter='all';selectedEmployee=null;render();};document.querySelector('#reviewMissing')?.addEventListener('click',()=>{activeView='team';teamFilter='missing';render();});document.querySelector('#viewAllAttention')?.addEventListener('click',()=>{activeView='team';teamFilter='missing';render();});document.querySelectorAll('.filter-tab').forEach(x=>x.addEventListener('click',()=>{teamFilter=x.dataset.filter;render();}));document.querySelectorAll('.employee-open').forEach(x=>x.addEventListener('click',()=>{selectedEmployee=x.dataset.id;render();}));document.querySelectorAll('.send-reminder').forEach(x=>x.addEventListener('click',ev=>{ev.stopPropagation();toast(`Reminder ready for ${x.dataset.name} — email sending is disabled in this demo.`)}));document.querySelector('#drawerClose')?.addEventListener('click',()=>{selectedEmployee=null;render();});document.querySelector('#drawerX')?.addEventListener('click',()=>{selectedEmployee=null;render();});document.querySelector('#employeeSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelector('#teamRows').innerHTML=teamRows((teamFilter==='missing'?missing:teamFilter==='complete'?compliant:employees).filter(x=>x.name.toLowerCase().includes(q)||x.id.toLowerCase().includes(q)));bind();});}
document.querySelector('#refreshButton').addEventListener('click',()=>toast('Sample data refreshed just now.'));
document.querySelector('#monthSwitcher').onchange=event=>{setMonth(event.target.value);activeView='overview';teamFilter='all';selectedEmployee=null;render();toast(`${data.month} sample data loaded.`)};
document.querySelector('#helpButton').addEventListener('click',()=>toast('Green means complete; purple means approved leave matched; red requires follow-up.'));
render();
