const sample = {
  instances: ['FINPRD01', 'FINDR01', 'HRPRD02'],
  tablespaces: [
    ['SYSTEM', 'Permanent', '32 GB', '20.5 GB', 64, 'Normal'], ['SYSAUX', 'Permanent', '28 GB', '21.2 GB', 76, 'Watch'],
    ['USERS', 'Permanent', '64 GB', '27.5 GB', 43, 'Normal'], ['FIN_DATA', 'Permanent', '512 GB', '438.4 GB', 86, 'Critical'],
    ['TEMP', 'Temporary', '48 GB', '12.3 GB', 26, 'Normal'], ['UNDO_TBS1', 'Undo', '96 GB', '48.7 GB', 51, 'Normal']
  ],
  sql: [
    ['8nzkw4p3p9j1r', 'SELECT * FROM GL_JE_LINES WHERE PERIOD_NAME = :p', 'FINAPP', '34.8%', '13.4 min'],
    ['7j4m0qsv89wdx', 'UPDATE AR_PAYMENT_SCHEDULES_ALL SET ...', 'AR_BATCH', '18.6%', '9.7 min'],
    ['9a3vct2p0btqm', 'SELECT /*+ FULL */ FROM XLA_AE_LINES', 'FINAPP', '14.2%', '7.1 min'],
    ['4p6kz1c8hx2df', 'MERGE INTO FND_LOG_MESSAGES ...', 'INTEGRATION', '8.9%', '4.0 min']
  ],
  objects: [
    ['GL_JE_LINES', 'FINANCE', 'Table', '18.4M', '12.8 GB', '3', 'Healthy'], ['AR_PAYMENT_SCHEDULES_ALL', 'FINANCE', 'Table', '9.2M', '7.3 GB', '4', 'Healthy'],
    ['XLA_AE_LINES', 'FINANCE', 'Table', '41.8M', '32.1 GB', '1', 'Missing index'], ['FND_LOG_MESSAGES', 'SYSTEM', 'Table', '11.1M', '5.8 GB', '2', 'Review'],
    ['PKG_GL_POSTING', 'FINANCE', 'Package', '—', '1.2 MB', '—', 'Valid'], ['PRC_AR_RECONCILE', 'FINANCE', 'Procedure', '—', '344 KB', '—', 'Valid']
  ],
  users: [
    ['FINAPP', 'Open', '2026-08-24', '2 days ago', 'DBA', 'Active'], ['AR_BATCH', 'Open', '2026-08-22', '4 hours ago', 'CONNECT', 'Active'],
    ['REPORTING_RO', 'Open', '2026-06-10', '75 days ago', 'READ_ONLY', 'Inactive'], ['LEGACY_ETL', 'Locked', '2025-04-08', '1 year, 4 months', 'CONNECT', 'Dormant'],
    ['TEMP_VENDOR', 'Expired', '2025-01-12', '1 year, 7 months', 'RESOURCE', 'Dormant'], ['SYS', 'Open', '2026-08-24', '1 day ago', 'SYSDBA', 'Active']
  ]
};

const content = document.querySelector('#appContent');
const pageTitle = document.querySelector('#pageTitle');
const pageEyebrow = document.querySelector('#pageEyebrow');
let currentPage = 'overview';

const lineChart = (color = '#3867f4', second = false) => `<svg viewBox="0 0 560 128" aria-label="24 hour trend chart" role="img"><g stroke="#edf0f5" stroke-width="1"><path d="M0 18H560M0 52H560M0 86H560M0 120H560"/></g><path d="M0 98 C20 94 28 84 49 86 S79 96 101 76 S130 55 151 68 S181 85 203 75 S234 42 254 53 S285 82 305 71 S334 23 355 40 S385 77 406 62 S436 83 458 68 S488 43 510 52 S539 30 560 36" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round"/>${second ? '<path d="M0 109 C37 103 71 111 101 95 S152 89 203 99 S257 82 305 94 S357 67 406 83 S458 78 510 87 S538 70 560 76" fill="none" stroke="#42c4d7" stroke-width="2.5" stroke-linecap="round"/>' : ''}</svg><div class="chart-labels"><span>00:00</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>Now</span></div>`;
const statusTag = (status) => `<span class="tag ${/Critical|Missing|Dormant|Expired/.test(status) ? 'red' : /Watch|Review/.test(status) ? 'warn' : /Active|Healthy|Valid|Normal/.test(status) ? '' : 'blue'}">${status}</span>`;
const table = (headers, rows, options = {}) => `<div class="table-scroll"><table class="data-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>`<td>${options.tags?.includes(i) ? statusTag(x) : x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const intro = (heading, copy, action = '') => `<div class="page-intro"><div><h2>${heading}</h2><p>${copy}</p></div>${action}</div>`;
const card = (title, body, sub = '', action = '') => `<article class="card"><div class="card-header"><div><h3>${title}</h3>${sub ? `<p>${sub}</p>` : ''}</div>${action}</div>${body}</article>`;

function overview(){
  return `${intro('Database overview', 'A real-time view of FINPRD01 · last data collection 09:42:18', '<div class="filter-group"><button class="select-btn">Last 24 hours⌄</button><button class="select-btn">Production⌄</button></div>')}
  <section class="kpis">
    <article class="kpi health-score card"><div class="kpi-label"><span>SYSTEM HEALTH SCORE</span><span class="healthy-pill">● HEALTHY</span></div><div class="score-main"><strong>92</strong><span>/ 100 · +3 since yesterday</span></div></article>
    <article class="kpi card"><div class="kpi-label"><span>CPU UTILIZATION</span><span>◌</span></div><div class="metric">42<span class="metric-unit">%</span></div><div class="metric-note">↓ 8% vs. 24h average</div></article>
    <article class="kpi card"><div class="kpi-label"><span>MEMORY USAGE</span><span>▤</span></div><div class="metric">68<span class="metric-unit">%</span></div><div class="metric-note warn">↑ 4% vs. 24h average</div></article>
    <article class="kpi card"><div class="kpi-label"><span>ACTIVE SESSIONS</span><span>◉</span></div><div class="metric">186</div><div class="metric-note">of 500 licensed sessions</div></article>
    <article class="kpi card"><div class="kpi-label"><span>OPEN ALERTS</span><span>△</span></div><div class="metric">3</div><div class="metric-note bad">1 requires attention</div></article>
  </section>
  <section class="grid-two">${card('Resource utilization', `<div class="chart-wrap"><div class="legend"><span><i></i>CPU utilization</span><span><i class="green"></i>Memory utilization</span></div>${lineChart('#3867f4', true)}</div>`, '24-hour rolling average', '<button class="link-button" data-goto="performance">VIEW PERFORMANCE →</button>')}${card('Database capacity', `<div class="donut-row"><div class="donut"><div>1.24<small>TB used of 2 TB</small></div></div><div class="capacity-list"><div class="capacity-item">FIN_DATA <span>86%</span><div class="progress"><i class="orange" style="width:86%"></i></div></div><div class="capacity-item">SYSAUX <span>76%</span><div class="progress"><i class="cyan" style="width:76%"></i></div></div><div class="capacity-item">USERS <span>43%</span><div class="progress"><i style="width:43%"></i></div></div></div></div>`, 'Tablespace usage', '<button class="link-button" data-goto="storage">VIEW STORAGE →</button>')}</section>
  <section class="grid-bottom">${card('Attention required', `<div class="alert-list"><div class="alert"><div class="alert-icon red">!</div><div><b>FIN_DATA tablespace is above threshold</b><p>86% used · 72 GB remaining · threshold 85%</p></div><time>09:31</time></div><div class="alert"><div class="alert-icon">!</div><div><b>Long-running SQL detected</b><p>SQL ID 8nzkw4p3p9j1r has run for 13m 24s</p></div><time>09:17</time></div><div class="alert"><div class="alert-icon">!</div><div><b>2 users inactive for more than 12 months</b><p>LEGACY_ETL and TEMP_VENDOR should be reviewed</p></div><time>08:45</time></div></div>`, '3 alerts from the last 24 hours', '<button class="link-button" data-goto="security">REVIEW ALL →</button>')}${card('Recent activity', `<div class="activity-list"><div class="activity"><i class="activity-dot green"></i><div><b>RMAN backup completed successfully</b><p>FINPRD01 · 09:12 · 412 GB archived</p></div></div><div class="activity"><i class="activity-dot"></i><div><b>Database statistics collection completed</b><p>FINANCE schema · 08:30 · 124 objects analyzed</p></div></div><div class="activity"><i class="activity-dot orange"></i><div><b>New execution plan captured</b><p>SQL ID 8nzkw4p3p9j1r · 08:04</p></div></div></div>`, 'Latest database events')}</section>`;
}

function performance(){return `${intro('Performance monitor','Watch workload pressure, waits, and expensive SQL statements.','<div class="filter-group"><button class="select-btn">Last 24 hours⌄</button></div>')}<section class="kpis"><article class="kpi card"><div class="kpi-label"><span>CPU</span><span>◌</span></div><div class="metric">42<span class="metric-unit">%</span></div><div class="metric-note">Within target &lt; 70%</div></article><article class="kpi card"><div class="kpi-label"><span>DB TIME</span><span>◷</span></div><div class="metric">1.82<span class="metric-unit"> s</span></div><div class="metric-note warn">↑ 12% vs baseline</div></article><article class="kpi card"><div class="kpi-label"><span>LOGONS / SEC</span><span>↗</span></div><div class="metric">14.7</div><div class="metric-note">Normal workload</div></article><article class="kpi card"><div class="kpi-label"><span>BLOCKED SESSIONS</span><span>⊗</span></div><div class="metric">2</div><div class="metric-note warn">Investigate if persistent</div></article><article class="kpi card"><div class="kpi-label"><span>AVG. RESPONSE</span><span>⌁</span></div><div class="metric">184<span class="metric-unit"> ms</span></div><div class="metric-note">SLA target: 250 ms</div></article></section><section class="grid-two">${card('Database time trend',`<div class="chart-wrap"><div class="legend"><span><i></i>Database time</span><span><i class="orange"></i>CPU time</span></div>${lineChart('#8067e8',true)}</div>`,'Active workload across the last 24 hours')}${card('Top wait events',`<div class="alert-list"><div class="alert"><div class="alert-icon">1</div><div><b>db file sequential read</b><p>38.4% of wait time · avg. wait 6.4 ms</p></div><time>IO</time></div><div class="alert"><div class="alert-icon">2</div><div><b>log file sync</b><p>21.7% of wait time · avg. wait 3.1 ms</p></div><time>COMMIT</time></div><div class="alert"><div class="alert-icon">3</div><div><b>enq: TX - row lock contention</b><p>12.1% of wait time · 2 waiting sessions</p></div><time>LOCK</time></div></div>`,'Events ranked by total wait time')}</section><section class="table-card card">${card('Top SQL by database time',table(['SQL ID','SQL TEXT','SCHEMA','DB TIME','ELAPSED'],sample.sql),'Click a SQL ID in a live integration to inspect its plan')}</section>`}

function storage(){const rows=sample.tablespaces.map(r=>[r[0],r[1],r[2],r[3],`<div class="progress"><i class="${r[4]>85?'orange':''}" style="width:${r[4]}%"></i></div><small>${r[4]}%</small>`,r[5]]);return `${intro('Storage monitor','Tablespace, ASM disk group, and operating-system filesystem capacity.','<div class="filter-group"><button class="select-btn">All tablespaces⌄</button></div>')}<section class="kpis"><article class="kpi card"><div class="kpi-label"><span>DATABASE SIZE</span><span>▣</span></div><div class="metric">1.24<span class="metric-unit"> TB</span></div><div class="metric-note">62% of allocated capacity</div></article><article class="kpi card"><div class="kpi-label"><span>FREE SPACE</span><span>◫</span></div><div class="metric">760<span class="metric-unit"> GB</span></div><div class="metric-note">Across all tablespaces</div></article><article class="kpi card"><div class="kpi-label"><span>ARCHIVE LOG</span><span>▤</span></div><div class="metric">46<span class="metric-unit">%</span></div><div class="metric-note">2.8 TB free on FRA</div></article><article class="kpi card"><div class="kpi-label"><span>DATAFILES</span><span>▥</span></div><div class="metric">386</div><div class="metric-note">12 autoextensible</div></article><article class="kpi card"><div class="kpi-label"><span>GROWTH / MONTH</span><span>↗</span></div><div class="metric">38<span class="metric-unit"> GB</span></div><div class="metric-note warn">↑ 9% vs. last month</div></article></section><section class="table-card card">${card('Tablespace utilization',table(['TABLESPACE','TYPE','ALLOCATED','USED','UTILIZATION','STATUS'],rows,{tags:[5]}),'FIN_DATA needs capacity planning within the next 14 days')}</section><section class="split-columns"><div>${card('ASM disk groups',table(['DISK GROUP','TOTAL','USABLE','USED','REDUNDANCY'],[['+DATA','2.0 TB','760 GB','62%','Normal'],['+RECO','4.0 TB','2.8 TB','30%','Normal']]),'Automatic Storage Management')}</div><div>${card('Host filesystems',table(['MOUNT','SIZE','USED','AVAILABLE','STATUS'],[[' /u01','250 GB','184 GB','66 GB','Normal'],[' /u02','500 GB','444 GB','56 GB','Watch'],[' /backup','2 TB','1.1 TB','900 GB','Normal']]),'Database server: fin-db-prd-01')}</div></section>`}

function database(){return `${intro('Database objects','Inventory, object health, and index coverage across database schemas.','<div class="filter-group"><button class="select-btn">All schemas⌄</button><button class="select-btn">Export inventory</button></div>')}<section class="kpis"><article class="kpi card"><div class="kpi-label"><span>TABLES</span><span>▦</span></div><div class="metric">2,846</div><div class="metric-note">46 created this month</div></article><article class="kpi card"><div class="kpi-label"><span>INDEXES</span><span>⌘</span></div><div class="metric">5,912</div><div class="metric-note">98.7% valid</div></article><article class="kpi card"><div class="kpi-label"><span>PACKAGES</span><span>▤</span></div><div class="metric">684</div><div class="metric-note">3 invalid objects</div></article><article class="kpi card"><div class="kpi-label"><span>PROCEDURES</span><span>⌁</span></div><div class="metric">1,119</div><div class="metric-note">All compiled</div></article><article class="kpi card"><div class="kpi-label"><span>INVALID OBJECTS</span><span>△</span></div><div class="metric">3</div><div class="metric-note bad">Requires review</div></article></section><section class="grid-two">${card('Object distribution',`<div class="donut-row"><div class="donut" style="background:conic-gradient(#3867f4 0 43%,#8067e8 43% 69%,#42c4d7 69% 87%,#f39a3c 87% 100%)"><div>10.6<small>K total objects</small></div></div><div class="capacity-list"><div class="capacity-item">Indexes <span>5,912</span><div class="progress"><i style="width:86%"></i></div></div><div class="capacity-item">Tables <span>2,846</span><div class="progress"><i class="cyan" style="width:53%"></i></div></div><div class="capacity-item">PL/SQL objects <span>1,803</span><div class="progress"><i class="orange" style="width:34%"></i></div></div></div></div>`,'Object inventory by type')}${card('Index health',`<div class="stat-bar"><div><b>5,836</b>Usable indexes</div><div><b>42</b>Unused indexes</div><div><b>34</b>Invalid indexes</div></div><div class="alert-list"><div class="alert"><div class="alert-icon red">!</div><div><b>XLA_AE_LINES has a missing index candidate</b><p>Full scans account for 14.2% of database time</p></div></div><div class="alert"><div class="alert-icon">!</div><div><b>34 indexes require rebuild review</b><p>Fragmentation is above the configured threshold</p></div></div></div>`,'Index coverage and maintenance')}</section><section class="table-card card">${card('Largest and most active objects',table(['OBJECT NAME','OWNER','TYPE','ROWS','SIZE','INDEXES','STATUS'],sample.objects,{tags:[6]}),'Object catalogue · sample extract')}</section>`}

function security(){return `${intro('Users & security','Review database access, account status, and inactive user accounts.','<div class="filter-group"><button class="select-btn" id="inactiveToggle">Show inactive only</button><button class="select-btn">All profiles⌄</button></div>')}<section class="kpis"><article class="kpi card"><div class="kpi-label"><span>TOTAL USERS</span><span>♙</span></div><div class="metric">218</div><div class="metric-note">12 created this month</div></article><article class="kpi card"><div class="kpi-label"><span>OPEN ACCOUNTS</span><span>◉</span></div><div class="metric">174</div><div class="metric-note">79.8% of all accounts</div></article><article class="kpi card"><div class="kpi-label"><span>INACTIVE 90+ DAYS</span><span>◷</span></div><div class="metric">17</div><div class="metric-note warn">Account review recommended</div></article><article class="kpi card"><div class="kpi-label"><span>INACTIVE 1+ YEAR</span><span>△</span></div><div class="metric">2</div><div class="metric-note bad">Action required</div></article><article class="kpi card"><div class="kpi-label"><span>LOCKED / EXPIRED</span><span>⊗</span></div><div class="metric">31</div><div class="metric-note">System-managed accounts included</div></article></section><section class="grid-two">${card('Login activity',`<div class="chart-wrap"><div class="legend"><span><i></i>Successful logins</span><span><i class="orange"></i>Failed attempts</span></div>${lineChart('#42c4d7',true)}</div>`,'Authentication events over the last 24 hours')}${card('Security attention',`<div class="alert-list"><div class="alert"><div class="alert-icon red">!</div><div><b>2 users have not logged in for over a year</b><p>LEGACY_ETL and TEMP_VENDOR</p></div></div><div class="alert"><div class="alert-icon">!</div><div><b>7 accounts have passwords expiring in 14 days</b><p>Send advance notification to account owners</p></div></div><div class="alert"><div class="alert-icon">!</div><div><b>3 users retain DBA role privileges</b><p>Next privilege review due Sep 01, 2026</p></div></div></div>`,'Prioritize the following actions')}</section><section class="table-card card">${card('Database user directory',table(['USERNAME','ACCOUNT STATUS','LAST LOGIN','INACTIVE FOR','PROFILE','REVIEW'],sample.users,{tags:[1,5]}),'Inactive accounts are highlighted for access review')}</section>`}

const pages={overview,performance,storage,database,security};
function render(page){currentPage=page;content.innerHTML=pages[page]();const meta={overview:['Good morning, Manivas','ORACLE DATABASE MONITORING'],performance:['Performance monitor','ORACLE DATABASE MONITORING'],storage:['Storage monitor','ORACLE DATABASE MONITORING'],database:['Database objects','ORACLE DATABASE MONITORING'],security:['Users & security','ORACLE DATABASE MONITORING']}[page];pageTitle.textContent=meta[0];pageEyebrow.textContent=meta[1];document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.goto)));const inactive=document.querySelector('#inactiveToggle');if(inactive) inactive.addEventListener('click',()=>{const rows=sample.users.filter(r=>r[5]==='Dormant');document.querySelector('.table-card').innerHTML=card('Inactive users requiring review',table(['USERNAME','ACCOUNT STATUS','LAST LOGIN','INACTIVE FOR','PROFILE','REVIEW'],rows,{tags:[1,5]}),'Accounts without login activity for at least one year');inactive.textContent='Showing inactive users';});}
document.querySelectorAll('.nav-link').forEach(button=>button.addEventListener('click',()=>render(button.dataset.page)));
document.querySelector('#refreshButton').addEventListener('click',()=>{const toast=document.querySelector('#toast');toast.textContent='Sample monitoring data refreshed at '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});toast.classList.add('show');document.querySelector('#sidebarRefresh').textContent='just now';setTimeout(()=>toast.classList.remove('show'),2500)});
document.querySelector('#instanceSwitcher').addEventListener('click',()=>{const el=document.querySelector('#instanceName');const next=sample.instances[(sample.instances.indexOf(el.textContent)+1)%sample.instances.length];el.textContent=next;document.querySelector('#toast').textContent='Switched to '+next+' (sample environment)';document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),2200)});
render('overview');
